import React from "react";
import Head from "next/head";
import Hero from "../components/Hero";
import SliderData from "../components/SliderData";
import ImageSlider from "../components/ImageSlider";
import Services from "../components/Services";
import Sidebar from "../components/Sidebar";

const Home = () => {
  return (
    <div>
      <Head>
        <title>GODZ LLC</title>
        <meta name="description" content="Generated by Next.js" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Hero
          heading="GODZ LLC"
          message="Building and inspiring inner GODZ LLC, One click at a time."
        />
        {/*<ImageSlider slides={SliderData} /> */}
        <Services />
      </div>
  );
};

export default Home;
